### PR TITLE
Fix WASM support in Nakama and Satori

### LINKED ISSUE #125: Nakama is not supported WASM.
Unsupported operation: Nakama is not supported outside IO/JS runtime.

### PR DESCRIPTION
**Pull request by ilmalte**
Fix WASM support in Nakama and Satori by using `dart.library.js_interop` conditional imports

WASM environments do not expose `dart.library.js`, causing the stub implementation (which throws UnsupportedError) to be incorrectly selected instead of the proper web client.

## Solution
- Use `dart.library.js_interop` conditional import to select the correct client implementation on WASM
- Since the SDK constraint is `^3.8.0` (minimum Dart 3.8), the `dart.library.js_interop` is always available, making fallbacks unnecessary
- Inline `preparePayload()` calls and remove the wrapper function for clarity (WASM uses gRPC, no RPC via REST needed)
- Add gRPC RPC tests to complement existing REST RPC tests

## Changes
- `nakama/lib/nakama.dart`: Add conditional import for `dart.library.js_interop`
- `satori/lib/satori.dart`: Add conditional import for `dart.library.js_interop`
- `nakama/lib/src/utils/prepare_payload.dart`: Remove wrapper function, inline `jsonEncode()` calls
- `nakama/test/rest/rpc_test.dart`: Add gRPC RPC tests
- Remove auto-generated proto methods (`createRepeated()`) from internal proto files (already removed in PR #169)

## Note
This PR is dependent on PR #169 for some changes already merged to main.

### CODE REVIEW

File: nakama/lib/nakama.dart [hunk 1]
```diff
@@ -27,5 +27,7 @@ export 'src/nakama_client/nakama_client.dart';
 export 'src/nakama_client/nakama_grpc_client.dart';
 export 'src/nakama_client/stub/nakama_client_stub.dart'
     if (dart.library.io) './src/nakama_client/stub/grpc_client.dart'
+    if (dart.library.js_interop) './src/nakama_client/stub/api_client.dart'
+    // Fallback: dart.library.js_interop is not available for Dart SDKs < 3.3
```
Comment (DannyIsYog) [inline nakama/lib/nakama.dart]: the pubspec.yaml SDK constraint is ^3.8.0, so Dart < 3.3 can never use this package. The fallback is unreachable so it can be removed?

File: nakama/lib/src/utils/prepare_payload.dart [hunk 2]
```diff
@@ -1,9 +1,6 @@
 import 'dart:convert';
 
-import 'package:nakama/src/utils/stub/platform_stub.dart'
-    if (dart.library.io) 'package:nakama/src/utils/stub/platform_io.dart'
-    if (dart.library.js) 'package:nakama/src/utils/stub/platform_web.dart';
-
+/// Prepares the RPC payload for sending via REST API.
 String preparePayload(String payload) {
-  return isWeb ? jsonEncode(payload) : payload;
+  return jsonEncode(payload);
```
Comment (DannyIsYog) [inline nakama/lib/src/utils/prepare_payload.dart]: Now that it unconditionally calls jsonEncode, shouldn't this file be removed all togehter? Inline it at the call site and remove the file?

File: nakama/lib/src/api/proto/google/protobuf/empty.pb.dart [hunk 3]
```diff
@@ -55,7 +55,6 @@ class Empty extends $pb.GeneratedMessage {
   static Empty create() => Empty._();
   @$core.override
   Empty createEmptyInstance() => create();
-  static $pb.PbList<Empty> createRepeated() => $pb.PbList<Empty>();
```
Comment (DannyIsYog) [inline nakama/lib/src/api/proto/google/protobuf/empty.pb.dart:58]: The removal of createRepeated() from the proto files is a breaking change to the public API, should we consider bumping the version of the sdk?

File: nakama/test/rest/rpc_test.dart
Comment (DannyIsYog) [inline nakama/test/rest/rpc_test.dart:1]: Should we also add a gRPC RPC test?

File: nakama/lib/nakama.dart (hunk 1 above)
Comment (ilmalte) [reply nakama/lib/nakama.dart]: Correct! I wasn't sure about this but with sdk: ^3.8.0 that fallback can never be reached. For some reason I was quite sure I did read somewhere it was possible to still use this base to support older versions.

File: nakama/lib/src/utils/prepare_payload.dart (hunk 2 above)
Comment (ilmalte) [reply nakama/lib/src/utils/prepare_payload.dart]: I thought keeping it wrapped in a named function made the intent clearer, but you perceived this way I am more convinced jsonEncode is explicit enough. I'll make it inline and delete the file.

File: nakama/test/rest/rpc_test.dart
Comment (ilmalte) [reply nakama/test/rest/rpc_test.dart:1]: It's a good idea, I'll mirror the REST while using the gRPC connection so we can test/track both.

File: nakama/lib/src/api/proto/google/protobuf/empty.pb.dart (hunk 3 above)
Comment (ilmalte) [reply nakama/lib/src/api/proto/google/protobuf/empty.pb.dart:58]: This was actually removed in PR #169 (already in main).

These are auto-generated proto internal files (under lib/src/).
To my knowledge, in order for consumers to be affected by this change they should have explicitly imported these internals. The only public API is what's explicitly exported from lib/nakama.dart. Plus I didn't find any transitive call to that method so we should be safe to delete without any version bump :)

**Review by DannyIsYog — APPROVED** [review]
